name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run tests
        run: go test -v ./...

      - name: Build binaries
        run: |
          # Build for multiple platforms
          GOOS=linux GOARCH=amd64 go build -ldflags="-X main.version=${{ github.ref_name }} -X main.commit=${{ github.sha }}" -o authguard-linux-amd64 ./cmd/authguard
          GOOS=linux GOARCH=arm64 go build -ldflags="-X main.version=${{ github.ref_name }} -X main.commit=${{ github.sha }}" -o authguard-linux-arm64 ./cmd/authguard
          GOOS=darwin GOARCH=amd64 go build -ldflags="-X main.version=${{ github.ref_name }} -X main.commit=${{ github.sha }}" -o authguard-darwin-amd64 ./cmd/authguard
          GOOS=darwin GOARCH=arm64 go build -ldflags="-X main.version=${{ github.ref_name }} -X main.commit=${{ github.sha }}" -o authguard-darwin-arm64 ./cmd/authguard
          GOOS=windows GOARCH=amd64 go build -ldflags="-X main.version=${{ github.ref_name }} -X main.commit=${{ github.sha }}" -o authguard-windows-amd64.exe ./cmd/authguard

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dhiagharsallaoui/authguard
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ github.ref_name }}
            COMMIT=${{ github.sha }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          generate_release_notes: true
          files: |
            authguard-linux-amd64
            authguard-linux-arm64
            authguard-darwin-amd64
            authguard-darwin-arm64
            authguard-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
